- name: Add Amazon EC2 provider into CloudForms
  uri:
    url: "{{ manageiq_provider_url }}"
    method: POST
    body:
      name: "{{ ec2_provider_name }}"
      type: "{{ ec2_provider_type }}"
      credentials: "{{ ec2_provider_credentials }}"
      zone: "{{ ec2_provider_zone }}"
      action: create
      provider_region: "{{ ec2_region }}"
    body_format: json
    validate_certs: False
    headers:
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: "application/json" 
    status_code: 200
  register: provider_info
  ignore_errors: True

- name: debug add of provider
  debug: msg="{{ provider_info }}"

- name: Adding provider suceeded
  set_fact: prov_id="{{ provider_info.json.results[0].id }}"
  when: provider_info.status == '200'

- name: Provider exists -  get its ID
  uri:
    url: "{{ manageiq_provider_url }}?expand=resources&attributes=name,id&filter[]=name={{ ec2_provider_name }}"
    method: GET
    body_format: json
    validate_certs: False
    headers:
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: "application/json" 
    status_code: 200
  when: provider_info.json.error is defined and "'Name has already been taken' in provider_info.json.error.message"
  register: get_prov_id

- name: debug my vars
  debug: msg="{{ get_prov_id }}"

- name: Adding provider failed - provider exists?
  set_fact: prov_id="{{ get_prov_id.json.resources[0]['id'] }}"
  when: get_prov_id.skipped == 'false'

#- debug: msg="{{ get_prov_id.json.resources[0]['id'] }}"
#- debug: msg="{{ get_prov_id.json.resources[0]['href'] }}"

#- set_fact: prov_id="{{ get_prov_id.json.resources[0]['id'] }}"
#  when: "'Name has already been taken' in provider_info.json.error.message"

#- debug: msg="{{ provider_info }}"
#- set_fact: prov_id="{{ provider_info.json.results[0].id }}"
#  when: provider_info.status == '200'
  

#https://10.8.196.164/api/providers?expand=resources&attributes=id,name&filter[]=name='ec2_provider_eu-central-1'
