#- set_fact: prov_id="{{ provider_info.json.results[0].id }}"

- name: Register why provider exists?
  #set_fact: prov_id="{{ get_prov_id.json.resources[0]['id'] }}"
  set_fact: failed_add_prov = 'yes'
  when: provider_info.status != '200'
  #when: provider_info.status != '200' and "'Name has already been taken' in provider_info.json.error.message"

- name: Adding provider failed - provider exists?
  set_fact: prov_id="{{ get_prov_id.json.resources[0]['id'] }}"
  register: failed_add_prov
  when: failed_add_prov is defined and "'Name has already been taken' in provider_info.json.error.message"

#- debug: msg="{{ provider_info }}"
- name: Adding provider suceeded
  set_fact: prov_id="{{ provider_info.json.results[0].id }}"
  when: provider_info.status == '200'

- name: Wait few seconds after adding provider, otherwise you can get response "Providers failed last authentication check"
  pause: seconds="{{ wait_seconds_before_refresh }}"

- name: Refresh Amazon EC2 provider in CloudForms
  uri:
    url: "{{ manageiq_provider_url }}/{{ prov_id }}"
    method: POST
    body:
      action: refresh
    body_format: json
    validate_certs: False
    headers:
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: "application/json" 
    status_code: 200
  register: output

- debug: msg="{{ output }}"

- name: set the task href
  set_fact:
    task_url: "{{ output.json.task_href}}"

- name: Wait for the refresh to end
  uri:
    url: "{{ task_url }}"
    method: GET
    validate_certs: False
    headers:
      X-Auth-Token: "{{ auth_token }}"
      Content-Type: "application/json" 
    status_code: 200
  register: task_result
  until: task_result.json.state == 'Finished' or task_result.json.status == 'Error'
  failed_when: task_result.json.status == 'Error'
  retries: "{{max_retries}}"
  delay: "{{retry_interval}}"
